application: jlank-istm6205-ae01
version: 1
runtime: python
api_version: 1

handlers:
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static

- url: /css/bootstrap/css/bootstrap.css
  static_files: static/css/bootstrap/css/bootstrap.css
  upload: static/css/bootstrap/css/bootstrap.css
